// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGJYwMRxvSotSKMU58djaHvGu7d2rBzkI',
    appId: '1:170021392763:web:c91909a99e3a64257dedde',
    messagingSenderId: '170021392763',
    projectId: 'intweet-8f725',
    authDomain: 'intweet-8f725.firebaseapp.com',
    storageBucket: 'intweet-8f725.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxwPA4EYsFCGBaKzrAS8jBv3bzLxxkeZM',
    appId: '1:170021392763:android:24002770181fa5117dedde',
    messagingSenderId: '170021392763',
    projectId: 'intweet-8f725',
    storageBucket: 'intweet-8f725.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwgrX6Fo8YH3QD0WAYR5buuws48WGgonw',
    appId: '1:170021392763:ios:ba339198c4aaf2b07dedde',
    messagingSenderId: '170021392763',
    projectId: 'intweet-8f725',
    storageBucket: 'intweet-8f725.appspot.com',
    iosClientId:
        '170021392763-9no3kvg9ts52eaj2up5k6ctirv8hl3qe.apps.googleusercontent.com',
    iosBundleId: 'com.example.intweetAplikation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwgrX6Fo8YH3QD0WAYR5buuws48WGgonw',
    appId: '1:170021392763:ios:ba339198c4aaf2b07dedde',
    messagingSenderId: '170021392763',
    projectId: 'intweet-8f725',
    storageBucket: 'intweet-8f725.appspot.com',
    iosClientId:
        '170021392763-9no3kvg9ts52eaj2up5k6ctirv8hl3qe.apps.googleusercontent.com',
    iosBundleId: 'com.example.intweetAplikation',
  );
}
